### ISSUE TITLE
conda install -c cyz931123 r-scgnnltmg

### ISSUE THREAD

**Issue by clay001** [juexinwang/scGNN#15]
which command should I ran if I get ? 
> PackagesNotFoundError: The following packages are not available from current channels:

  - r-scgnnltmg

**Comment by juexinwang** [comment]
Hi,
Please use `coda install -c cyz931123 r-scgnnltmg` to install.

We tested in the following enviroment：

(myenv) cyz@Yuzhou:envs$ conda list -n myenv
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_r-mutex                  1.0.0               anacondar_1  
binutils_impl_linux-64    2.33.1               he6710b0_7  
binutils_linux-64         2.33.1              h9595d00_15  
bwidget                   1.9.11                        1  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.10.14                    0  
cairo                     1.14.12              h8948797_3  
curl                      7.69.1               hbc83047_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
fribidi                   1.0.10               h7b6447c_0  
gcc_impl_linux-64         7.3.0                habb00fd_1  
gcc_linux-64              7.3.0               h553295d_15  
gfortran_impl_linux-64    7.3.0                hdf63c60_1  
gfortran_linux-64         7.3.0               h553295d_15  
glib                      2.66.1               h92f7085_0  
graphite2                 1.3.14               h23475e2_0  
gsl                       2.4                  h14c3975_4  
gxx_impl_linux-64         7.3.0                hdf63c60_1  
gxx_linux-64              7.3.0               h553295d_15  
harfbuzz                  2.4.0                hca77d97_1  
icu                       58.2                 he6710b0_3  
jpeg                      9b                   h024ee3a_2  
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.69.1               h20c2e04_0  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.2                heb0550a_3  
make                      4.2.1                h1bed415_1  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1h               h7b6447c_0  
pango                     1.45.3               hd140c19_0  
pcre                      8.44                 he6710b0_0  
pixman                    0.40.0               h7b6447c_0  
r-base                    3.6.1                haffb61f_2  
r-lattice                 0.20_38           r36h96ca727_0  
r-matrix                  1.2_17            r36h96ca727_0  
r-scgnnltmg               0.1.0                     r36_0    cyz931123
readline                  8.0                  h7b6447c_0  
tk                        8.6.10               hbc83047_0  
tktable                   2.10                 h14c3975_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0
